info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T04:59:06.805Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-19T04:59:06.943Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T04:59:49.944Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-19T04:59:50.026Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T04:59:58.484Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-19T04:59:58.598Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:00:08.748Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/Fundo_Backend_app/FundoBackendApp/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-19T05:00:08.867Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:00:57.384Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:00:57.556Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:01:18.017Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:01:18.194Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:01:42.327Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:02:10.367Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:02:22.733Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:02:49.161Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:03:04.309Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:03:17.078Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:03:28.677Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:03:37.763Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:03:56.019Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:03:56.202Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:04:14.687Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:04:14.940Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:04:23.600Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:04:24.058Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:04:46.271Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:05:04.546Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:05:27.498Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:06:02.742Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:06:17.154Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:06:30.736Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:06:48.711Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:07:28.257Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:07:28.442Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:07:32.849Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:07:33.025Z"}
info: Server started at http://localhost:3008/api/v1/ {"timestamp":"2024-07-19T05:08:45.708Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:08:45.889Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:09:38.978Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:09:39.234Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:10:10.927Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:10:11.268Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:10:11.293Z"}
info: Server started at http://localhost:3009/api/v1/ {"timestamp":"2024-07-19T05:17:07.853Z"}
info: Connected to the database. {"timestamp":"2024-07-19T05:17:08.731Z"}
